package enums;

public enum EquipTypeEnum {
    PROJECTOR,
    WHITEBOARD,
    CHAIR,
    TABLE,
    HEATER,
    PLANT,
    AIR_CONDITIONER,
    VENTILATION_SYSTEM,
    FIRE_EXTINGUISHER,
    FIRE_ALARM,
    TOILET,
    SINK,
    URINAL,
    ALARM_SYSTEM,
    CAMERA,
    PRINTER,
    EMERGENCY_LIGHTING,
    ROUTER,
    SPRINKLER_SYSTEM,
    LAMP,
    TELEPHONE_SYSTEM,
    SECURITY_DOOR
}
